name: Build and publish release JAR

on:
  push:
    tags:
      - 'v*'   # Trigger khi push tag bắt đầu bằng v, ví dụ v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Find built JAR
        id: find_jar
        run: |
          JAR=$(ls target/*.jar | head -n 1 || true)
          if [ -z "$JAR" ]; then
            echo "No JAR found in target/"; exit 1
          fi
          echo "jar_path=$JAR" >> $GITHUB_OUTPUT
        shell: bash

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Create GitHub Release and Upload JAR
        run: |
          gh release create ${{ github.ref_name }} ${{ steps.find_jar.outputs.jar_path }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for ${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
